package Views;

import Application.ApplicationDesktop;
import javax.swing.JInternalFrame;

public class AppView extends javax.swing.JFrame {

    public AppView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        carreras = new javax.swing.JMenu();
        cursos = new javax.swing.JMenu();
        profesores = new javax.swing.JMenu();
        alumnos = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        cerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Académica");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("                           \n\n\n\n\n\n\t\t\t                      Bienvenido al Sistema de Gestion Academica.\n\n\n                                                    El Sistema de Gestion Academica (SisGesAca) brinda los servicios de informacion que permiten procesar la\n\t                       información de las carreras que ofrece, los cursos que las forman, los profesores que los imparten y los alumnos\n\t                       inscritos. Tambien ofrece la siguiente funcionalidad:\n\n\t                         * Gestionar cada ciclo lectivo, para lo cual debe abrir el ciclo como tal, registrar la oferta académica, es decir\n\t                       los cursos y grupos que se van a abrir y los profesores que los van a impartir.\n\n\t                         * Ejecutar el proceso de matrícula, en el cual se registran los cursos y grupos específicos que matricula cada\n\t                       estudiante.\n\n\t                         * Realizar el proceso final del ciclo, en el cual el profesor registra las notas que obtuvieron los estudiantes de sus\n\t                       grupos.");
        jTextArea1.setDisabledTextColor(new java.awt.Color(13, 0, 0));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1507, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);

        jMenu1.setText("SisGesAca  ");
        jMenuBar1.add(jMenu1);

        carreras.setText("Carreras");
        carreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrerasMouseClicked(evt);
            }
        });
        jMenuBar1.add(carreras);

        cursos.setText("Cursos");
        cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosMouseClicked(evt);
            }
        });
        jMenuBar1.add(cursos);

        profesores.setText("Profesores");
        profesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(profesores);

        alumnos.setText("Alumnos");
        alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosMouseClicked(evt);
            }
        });
        jMenuBar1.add(alumnos);

        jMenu2.setText(".                                                                                                                                                                                                                                                           .");
        jMenuBar1.add(jMenu2);

        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(cerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesoresMouseClicked
        ApplicationDesktop.PROFESORES_VIEW.setVisible(true);
        ApplicationDesktop.PROFESORES_VIEW.toFront();
    }//GEN-LAST:event_profesoresMouseClicked

    private void alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosMouseClicked
        ApplicationDesktop.ALUMNOS_VIEW.setVisible(true);
        ApplicationDesktop.ALUMNOS_VIEW.toFront();

    }//GEN-LAST:event_alumnosMouseClicked

    private void carrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrerasMouseClicked
        ApplicationDesktop.CARRERAS_VIEW.setVisible(true);
        ApplicationDesktop.CARRERAS_VIEW.toFront();
    }//GEN-LAST:event_carrerasMouseClicked

    private void cursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosMouseClicked
        ApplicationDesktop.CURSOS_VIEW.setVisible(true);
        ApplicationDesktop.CURSOS_VIEW.toFront();
    }//GEN-LAST:event_cursosMouseClicked

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        this.setVisible(false);
        ApplicationDesktop.LOGIN_CONTROLLER.cerrarSesion();
    }//GEN-LAST:event_cerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AppView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alumnos;
    private javax.swing.JMenu carreras;
    private javax.swing.JMenu cerrarSesion;
    private javax.swing.JMenu cursos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu profesores;
    // End of variables declaration//GEN-END:variables

    public void addInternalFrame(JInternalFrame f) {
        this.jDesktopPane1.add(f);
    }
}
