package Views;

import Application.ApplicationDesktop;
import javax.swing.JInternalFrame;

public class AppView extends javax.swing.JFrame {


    public AppView(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        carreras = new javax.swing.JMenu();
        cursos = new javax.swing.JMenu();
        profesores = new javax.swing.JMenu();
        alumnos = new javax.swing.JMenu();
        logOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión Académica");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1507, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);

        carreras.setText("Carreras");
        carreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrerasMouseClicked(evt);
            }
        });
        jMenuBar1.add(carreras);

        cursos.setText("Cursos");
        cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursosMouseClicked(evt);
            }
        });
        jMenuBar1.add(cursos);

        profesores.setText("Profesores");
        profesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(profesores);

        alumnos.setText("Alumnos");
        alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosMouseClicked(evt);
            }
        });
        jMenuBar1.add(alumnos);

        logOut.setText("Cerrar sesión");
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logOut);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesoresMouseClicked
        ApplicationDesktop.PROFESORES_VIEW.setVisible(true);
        ApplicationDesktop.PROFESORES_VIEW.toFront();
    }//GEN-LAST:event_profesoresMouseClicked

    private void alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosMouseClicked
        ApplicationDesktop.ALUMNOS_VIEW.setVisible(true);
        ApplicationDesktop.ALUMNOS_VIEW.toFront();
 
    }//GEN-LAST:event_alumnosMouseClicked

    private void carrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrerasMouseClicked
        ApplicationDesktop.CARRERAS_VIEW.setVisible(true);
        ApplicationDesktop.CARRERAS_VIEW.toFront();
    }//GEN-LAST:event_carrerasMouseClicked

    private void cursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursosMouseClicked
        ApplicationDesktop.CURSOS_VIEW.setVisible(true);
        ApplicationDesktop.CURSOS_VIEW.toFront();
    }//GEN-LAST:event_cursosMouseClicked

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alumnos;
    private javax.swing.JMenu carreras;
    private javax.swing.JMenu cursos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logOut;
    private javax.swing.JMenu profesores;
    // End of variables declaration//GEN-END:variables

   public void addInternalFrame(JInternalFrame f){
       this.jDesktopPane1.add(f);
   }
}
